[package]
name = "the_rust_lang_book"
version = "0.1.0"
edition = "2021"
authors = ["luismalamoc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
colored = "2.0.0"
